# Generated by Django 2.2 on 2020-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloaded',
            field=models.IntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
    ]
