# Generated by Django 2.2 on 2020-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_file_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access',
            field=models.CharField(choices=[('common', 'Общий'), ('hide', 'Скрытый'), ('private', 'Приватный')], default='common', max_length=20, verbose_name='Доступ'),
        ),
    ]
